### ISSUE TITLE
Feature extractors after cropping

### ISSUE THREAD

**Issue by Nadedic** [v-iashin/SparseSync#2]
Hello,

I am running inference with the model: `22-07-13T22-25-49` trained on LRS3 ('No Face Crop') and designed for speech for my usecase that falls under dense in space and time category where there is a single speaker in the center of the video.

During inference and reconstruction of the video that's fed to the model eventually, the video goes through a series of transformation including this method to crop the video to a square of 224*224 (as specified as `input_size`) 
https://github.com/v-iashin/SparseSync/blob/main/dataset/transforms.py#L95

Obviously, this is also used during training and testing and the exaplainion I found in the corresponing paper is: 
"The range of the temporal crop is limited such that the resulting clip could fit the audio that was offset as well as the visual clip."

Could you elaborate slightly on this? How would a window of size 512x512 be different than 224x224 in terms of offsetting audio? 
What is the point behind this number and what happens if we let the whole scene as ROI, I currently recieve memory errors but I am wondering if I could upgrade my hardware (expecting longer time span aswell) would it make sense? 

The main issue is that the resulting cropped ROI doesn't include the moving lip most of the time. (rather top right part as designed for the test video) in here: 
https://github.com/v-iashin/SparseSync/blob/main/data/lrs3/h264_uncropped_25fps_256side_16000hz_aac/pretrain/C8zY0oAdQrs/00018.mp4
And randomizing would not help me particularly if I know that the speaker is usually wound the center.

Sorry for long description but maybe I missed something?!

**Comment by v-iashin** [comment]
Hi there,

> "The range of the temporal crop is limited such that the resulting clip could fit the audio that was offset as well as the visual clip."

This note is about how the temporal crop is done. You seem to ask a question about the spatial crop.

Anyway, the "limiting" is related to time, not to space, and is done as follows. 

First, we pick the offset from the grid. Second, we pick a start time for the visual crop such that the offset audio's starting time would be inside of the video clip. 

For instance, if my offset is -1.0 seconds and the visual stream starts at 0.5 seconds, then the audio should start at -0.5 seconds and it is out of bounds. We want to avoid this. Therefore, we pick the start time of the visual crop from 1.0 seconds onwards until e.g. 5 seconds because if the visual crop starts at 6 seconds, it will end at 11 seconds which is again out of bounds.

> How would a window of size 512x512 be different than 224x224 in terms of offsetting audio?

As you can see, it does not matter. Sorry if you got confused here. First, we do the spatial crop (e.g. 224 out of 256). Then, temporal cropping and temporal offsetting are done in one of the next transformations.

> I currently receive memory errors

Is it RAM or GPU mem errors? Perhaps, you are trying to load long videos to your RAM. These can be quite brutal on RAM. What is the resolution, fps and length of a video you are trying to feed in? Do you scale your input videos? For instance, notice that all of the videos that are provided as examples are scaled to max(Height, Width) = 256. You are asking about 512, but I am not sure where did you get it.


> Sorry for long description but maybe I missed something?!

No problem. I think you got a few things confused but I hope this was helpful.

**Comment by Nadedic** [comment]
Thank you for the prompt response.

I have some more questions :)


> First, we pick the offset from the grid. Second, we pick a start time for the visual crop such that the offset audio's starting time would be inside of the video clip.
For instance, if my offset is -1.0 seconds and the visual stream starts at 0.5 seconds, then the audio should start at -0.5 seconds and it is out of bounds. We want to avoid this. Therefore, we pick the start time of the visual crop from 1.0 seconds onwards until e.g. 5 seconds because if the visual crop starts at 6 seconds, it will end at 11 seconds which is again out of bounds.

Not sure I understand how a visual stream can start at 0.5 seconds? Even if the speaker starts producing sound or sentences after 0.5 second but there is either some noise in the back , their "quite" frames would be considered in the visual stream meaning:
-> the visual offset is 0.0
-> the audio offset is 0.0  (or 0.5?)


---------------------------------------------------------------------------------------------------------
 within cfg-22-07-13T22-25-49 yaml -> dataset.transforms.RGBSpatialCrop transformation:
	Slightly increasing input_size to 240+ causes this error:
		 	
```
RuntimeError: CUDA error: device-side assert triggered
			CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
			For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
			
		Tracing it back to:	
			File Audio-Video-Desync/model/modules/attn_recorder.py:102, in Recorder.forward(self, *args)
				 99 off_loss, off_logits = self.transformer(*args)
				101 # move all recordings to one device before stacking
			  --> 102 recordings = tuple(map(lambda t: t.to(torch.device('cpu')), self.recordings))
			...
				106     # (B, L, H, S, S) where S = 2 + tv*h*w + 1 + f*ta
```
				
Using CUDA:0 as device, solves the this error but then I'd face this incompatible sizes error :
```	
			Output exceeds the size limit. 
			
		Tracing it back to:
			File Audio-Video-Desync/model/modules/attn_recorder.py:111, in Recorder.forward(self, *args)
			109     att = self.reorganize_self_att(att, self.visual_block_shape, self.audio_block_shape)
			110 elif self.watch_module.__name__ == 'CrossAttention' and self.submodule_name == 'v_selector':
		 --> 111     att = self.reorganize_cross_att(att, self.visual_block_shape)
		...
			 89     B, L, heads, Ss, Sc = att.shape
		 ---> 90     att_dict = {self.submodule_name: {'context': att.reshape(B, L, heads, Ss, *context_shape)}}
			 91     return att_dict

		RuntimeError: shape '[1, 3, 8, 16, 16, 7, 7]' is invalid for input of size 393216
```

Would this mean that the model is only expecting a certain frame size to enfer with? (e.g not more than 240*240?)
		
---------------------------------------------------------------------------------------------------------
 Dataset:
As I am trying train from scratch using the same data. (I already accessed the lrs3 but I don't think I can utilize it with your implementation)

I am having troubles understanding how you'd download the videos from youtube. Was it done manually? How did you ensure RGB (25fps, H.264) and audio (16kHz, AAC) constraint? 
> mind that _ and - in video ids were replaced by 'S'

Does it mean that there no video ids originally contain 'S'? How would differntiate parsing the "S" to "-" or "_" because they don't always work.
			
	

---------------------------------------------------------------------------------------------------------
About top_k predictions: it is always within 0.2 seconds intervals (either 0.00, 0.2, 0.4, etc), correct?  Even setting the offset_sec = 0.1 would yield a positive 0.2 audio offset prediction (or maybe 0.00). Is this because how the data was labelled? I couldn't really find information about this without a deeper dive.

**Comment by v-iashin** [comment]
> Not sure I understand how a visual stream can start at 0.5 seconds

I think there is confusion somewhere. Imagine you have a 10-second video clip. Out of it, you crop a 5-second sub-clip starting at any random point within the 10-second clip. The 5-second visual stream may start at 0.5 seconds with respect to the 10-second clip and spans the temporal region from 0.5 to 5.5 seconds. If the audio track starts at 1.5 seconds and ends at 6.5 seconds, it means that the out-of-sync offset is +1 second or the audio is late by 1 second.

> Would this mean that the model is only expecting a certain frame size to enfer with? (e.g not more than 240*240?)

The model `22-07-13T22-25-49` is trained with 224x224 inputs. Please re-scale your videos to match them. Meaning that you may want to resize your 240x240 video clips into 224x224.

> I am having troubles understanding how you'd download the videos from youtube. Was it done manually?

There are scripts online. Let me leave it for you to figure out the rest. I hope you understand. Sorry.

> How did you ensure RGB (25fps, H.264) and audio (16kHz, AAC) constraint?

Once you will download them using one of the scripts you find online, it will be clear.

> Does it mean that there no video ids originally contain 'S'?

The LRS3 dataset renamed the video clips with something like: `x.replace('_', 'S').replace('-', 'S')` (perhaps to avoid non-alpha-numeric characters in the file paths). Keep this in mind, when downloading/processing the videos. 

> it is always within 0.2 seconds intervals (either 0.00, 0.2, 0.4, etc), correct? 

The prediction might not be correct because there isn't a perfect model. What we mean by "tolerance ±0.2" applies only for evaluation. However, I am not entirely sure what you mean.

**Comment by v-iashin** [comment]
> So it only makes sense if the prediction follow a similar pattern of tolerance ±0.2 but never less (e.g. ±0.1 or ±0.05). Do you think training with a smaller offset class may yeild more detailed predictions; e.g ±0.05 sec delay?

Actually, we use `jitter` around the grid. See these lines: https://github.com/v-iashin/SparseSync/blob/3a269762fcacd601c4ada46f3b3059e6a1717922/dataset/transforms.py#L319-L322

> the amount of random factors in there I wasn't reaching anywhere ... Do you have a clue what might be causing either issue?

Sorry, that piece is not particularly nice, I agree. 

Also, mind the duration of the vids you are using. We filtered out the videos that are shorter than 10 seconds.

**Comment by Nadedic** [comment]
> Also, mind the duration of the vids you are using. We filtered out the videos that are shorter than 10 seconds.

I finally got to start training, indeed, I had to filter out any video that's shorter than 10 seconds to start training.

If I train sync transformer only, training processeds but results are extremely bad, accuracy doesn't jump over 1% improvement and the learning rate is all over the place. I haven't tried training for longer than a day. Did you notice good curves early on? First 10 epochs or so? Or you'd recommend waiting longer?

Once I try to train either feature selector network I get this error: 

```
[INFO] 31 Jan 2023 16:27:00 - main 
    Saving logs and checkpoints @ ./logs/sync_models/23-01-31T16-26-26
[INFO] 31 Jan 2023 16:27:00 - main.dataset.transforms 
    Offset class grid: tensor([-2.0000, -1.8000, -1.6000, -1.4000, -1.2000, -1.0000, -0.8000, -0.6000,
        -0.4000, -0.2000,  0.0000,  0.2000,  0.4000,  0.6000,  0.8000,  1.0000,
         1.2000,  1.4000,  1.6000,  1.8000,  2.0000])
[INFO] 31 Jan 2023 16:27:00 - main.dataset.transforms 
    Offset class grid: tensor([-2.0000, -1.8000, -1.6000, -1.4000, -1.2000, -1.0000, -0.8000, -0.6000,
        -0.4000, -0.2000,  0.0000,  0.2000,  0.4000,  0.6000,  0.8000,  1.0000,
         1.2000,  1.4000,  1.6000,  1.8000,  2.0000])
[INFO] 31 Jan 2023 16:27:00 - main.dataset.lrs 
    During IO, the length of clips is limited to 11 sec
[INFO] 31 Jan 2023 16:27:00 - main.dataset.lrs 
    During IO, the length of clips is limited to 11 sec
[INFO] 31 Jan 2023 16:27:00 - main.dataset.lrs 
    train has 7380 items
[INFO] 31 Jan 2023 16:27:00 - main.dataset.lrs 
    During IO, the length of clips is limited to 11 sec
[INFO] 31 Jan 2023 16:27:00 - main.dataset.lrs 
    During IO, the length of clips is limited to 11 sec
[INFO] 31 Jan 2023 16:27:00 - main.dataset.lrs 
    valid has 820 items
[INFO] 31 Jan 2023 16:27:00 - main.dataset.lrs 
    During IO, the length of clips is limited to 11 sec
[INFO] 31 Jan 2023 16:27:00 - main.dataset.lrs 
    During IO, the length of clips is limited to 11 sec
[INFO] 31 Jan 2023 16:27:00 - main.dataset.lrs 
    test has 873 items
[INFO] 31 Jan 2023 16:27:03 - main.model.modules.feature_selector 
    Positional embedding module for selectors: PositionEmbeddingSelectors
[INFO] 31 Jan 2023 16:27:03 - main.model.modules.feature_selector 
    Selector has 16 selectors
[INFO] 31 Jan 2023 16:27:03 - main.model.modules.feature_selector 
    Positional embedding module for selectors: PositionEmbeddingSelectors
[INFO] 31 Jan 2023 16:27:03 - main.model.modules.feature_selector 
    Selector has 16 selectors
[INFO] 31 Jan 2023 16:27:22 - main 
    The number of parameters: 54.349 mil
train (0):   0% 0/1476 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main(cfg)
  File "main.py", line 39, in main
    train_sync(cfg)
  File "..//projects/av_desync/Audio-Video-Desync/./scripts/train_sync.py", line 108, in train
    loss, logits = model(vid, aud, targets)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "..//projects/av_desync/Audio-Video-Desync/./model/sync_model.py", line 33, in forward
    vis = self.vfeat_extractor(vis)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "..//projects/av_desync/Audio-Video-Desync/./model/modules/feature_extractors.py", line 208, in forward
    x = self.base(x)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "..//projects/av_desync/Audio-Video-Desync/./model/modules/feat_extractors/visual/s3d.py", line 143, in forward
    x1 = self.branch1(x)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "..//projects/av_desync/Audio-Video-Desync/./model/modules/feat_extractors/visual/s3d.py", line 84, in forward
    x = self.relu_s(x)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 98, in forward
    return F.relu(input, inplace=self.inplace)
  File "..//miniconda3/envs/sparse_sync/lib/python3.8/site-packages/torch/nn/functional.py", line 1442, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 0; 9.78 GiB total capacity; 7.68 GiB already allocated; 51.25 MiB free; 7.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by v-iashin** [comment]
> Did you notice good curves early on? First 10 epochs or so? Or you'd recommend waiting longer?

yep, I think you need to wait for longer:
<img width="1372" alt="Screenshot 2023-01-31 at 20 37 24" src="https://user-images.githubusercontent.com/14952597/215864600-b6af7ea5-f6e0-47dc-bfbc-717c7eb08ac9.png">

**Comment by v-iashin** [comment]
Anything you could add?

**Comment by Nadedic** [comment]
> Anything you could add?
Sadly, I could not replicate your results with your archeticture.
 I also was looking at another usecase with speech scenario or sparse in space and dense in time setup, I used your pretrained model for my baseline. Along with alot of your implementation, great thanks and lots of appreciatation for the quality of code.
