### ISSUE TITLE
pretrained weights for ResNetAudio

### ISSUE THREAD

**Issue by shp216** [v-iashin/SparseSync#6]
<config>
model:
  target: model.sync_model.AVSyncModel
  params:
    afeat_extractor:
      is_trainable: True
      target: model.modules.feature_extractors.ResNet18AudioFeatures
      params:
        # ckpt_path: null
        ckpt_path: ./logs/feature_extractors/22-06-24T08-10-33/ResNetAudio-22-06-24T08-10-33.pt 
        

Thank you for your excellent research. I would like to use ResNetAudio, but although the checkpoint path is specified in the config, the actual directory does not exist. Would it be possible to obtain the pretrained weights for ResNetAudio?

**Comment by v-iashin** [comment]
if you run any demo or example, it will fetch it for you.

alternatively, you could use `https://a3s.fi/swift/v1/AUTH_a235c0f452d648828f745589cde1219a/sync/ResNetAudio-22-06-24T08-10-33.pt` (see https://github.com/v-iashin/SparseSync/blob/a5bee8a047c0ebeec66b18d4ddf4c5f0ef098a4f/utils/utils.py#L11-L12)
